name: 'NPM Audit Action'
description: 'Run npm audit to check for vulnerabilities in Node.js projects.'
author: 'RuslanSem'
inputs:
  node-version:
    description: 'Specify the Node.js version to use (default: latest).'
    required: false
    default: 'latest'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run npm audit
      run: npm audit
branding:
  icon: 'shield'
  color: 'blue'
